#!/bin/bash
sudo groupadd nfsusers
sudo useradd -G nfsusers user1
echo "sample" | sudo passwd --stdin user1
sudo yum install nfs-utils -y
sudo mkdir -p /nfs/imports/share
echo "10.0.1.4:/nfs/exports/share /nfs/imports/share nfs defaults 0 0" | sudo tee -a /etc/fstab
sudo mount -fav
if [ $? -eq 0 ]; then
  sudo mount -a
  echo "NFS mount successful"
else
  echo "NFS mount failed"
fi
#this will be a dry run