#!/bin/bash

#Run the python script to get the updated ami

# touch "${PWD}/ami_id.txt"
python "${PWD}/retrieve_latest_ami.py"

#Create simple ansible playbook directory structure
touch ansible.cfg
mkdir -p inventory/group_vars
mkdir -p inventory/host_vars
mkdir -p roles/


